# Generated by Django 5.1.8 on 2025-09-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fingerprint",
            name="is_known",
        ),
        migrations.AddField(
            model_name="fingerprint",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fingerprint",
            name="gender",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="fingerprint",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fingerprint",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fingerprint",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Context/source, e.g. security, healthcare, visitor, etc.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fingerprint",
            name="id",
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
